[pytest]
markers =
    appconfig: AppConfig configuration endpoint tests
    health: Health endpoint tests
    firmware_get: Firmware GET endpoint tests
    firmware_delete: Firmware DELETE endpoint tests
    firmware_download: Firmware download endpoint tests
    firmware_status: Firmware status PATCH endpoint tests
    firmware_upload: Firmware upload error handling tests
    ota: OTA endpoint tests
    users: Users endpoint tests
    ui: Management UI tests
