"""
GET /registration-keys — list active registration keys for the authenticated user.

Requires the caller to be a registered FireFly-Cloud user (Cognito JWT).
Returns only keys generated by the calling user (matched via Cognito sub).
Expired keys are omitted (DynamoDB TTL removes them eventually, but we
filter by current time to avoid returning keys that are past their TTL
but not yet purged).
"""

import json
import os
import time

import boto3
from boto3.dynamodb.conditions import Attr

from shared.app_config import get_appconfig
from shared.logging_config import configure_logger

logging_config = get_appconfig(profile="logging")
logger = configure_logger(logging_config)

dynamodb = boto3.resource("dynamodb")
REGISTRATION_KEYS_TABLE_NAME = os.environ["DYNAMODB_REGISTRATION_KEYS_TABLE_NAME"]
registration_keys_table = dynamodb.Table(REGISTRATION_KEYS_TABLE_NAME)


def _response(status_code, body=None):
    resp = {
        "statusCode": status_code,
        "headers": {"Content-Type": "application/json"},
    }
    resp["body"] = json.dumps(body, default=str) if body is not None else ""
    return resp


def _get_claims(event):
    return (
        event.get("requestContext", {})
        .get("authorizer", {})
        .get("jwt", {})
        .get("claims", {})
    )


def lambda_handler(event, context):
    try:
        claims = _get_claims(event)
        sub = claims.get("sub")
        if not sub:
            return _response(401, {"message": "Unauthorized"})

        now = int(time.time())

        result = registration_keys_table.scan(
            FilterExpression=Attr("generated_by_sub").eq(sub) & Attr("ttl").gt(now)
        )

        keys = []
        for item in result.get("Items", []):
            keys.append({
                "key": item["key"],
                "generated_at": int(item.get("generated_at", item.get("ttl", 0) - 1800)),
                "expires_at": int(item["ttl"]),
            })

        keys.sort(key=lambda k: k["generated_at"])

        return _response(200, {"registration_keys": keys})

    except Exception:
        logger.exception("Unhandled exception")
        return _response(500, {"message": "Internal server error"})
