"""
POST /registration-keys — generate a one-time device registration key.

Requires the caller to be a registered FireFly-Cloud user (Cognito JWT).
Generates a 6-character uppercase alphanumeric key, stores it in DynamoDB
with a 30-minute TTL, and returns it to the caller.

The caller shares the key with a manufacturing operator who enters it in
the HW-Reg UI to complete device registration.
"""

import json
import os
import random
import string
import time

import boto3

from shared.app_config import get_appconfig
from shared.logging_config import configure_logger

logging_config = get_appconfig(profile="logging")
logger = configure_logger(logging_config)

dynamodb = boto3.resource("dynamodb")
REGISTRATION_KEYS_TABLE_NAME = os.environ["DYNAMODB_REGISTRATION_KEYS_TABLE_NAME"]
registration_keys_table = dynamodb.Table(REGISTRATION_KEYS_TABLE_NAME)

KEY_TTL_SECONDS = 1800
KEY_LENGTH = 6
KEY_ALPHABET = string.ascii_uppercase + string.digits


def _response(status_code, body=None):
    resp = {
        "statusCode": status_code,
        "headers": {"Content-Type": "application/json"},
    }
    resp["body"] = json.dumps(body, default=str) if body is not None else ""
    return resp


def _get_claims(event):
    return (
        event.get("requestContext", {})
        .get("authorizer", {})
        .get("jwt", {})
        .get("claims", {})
    )


def lambda_handler(event, context):
    try:
        claims = _get_claims(event)
        if not claims.get("sub"):
            return _response(401, {"message": "Unauthorized"})

        generated_by_sub   = claims.get("sub", "")
        generated_by_email = claims.get("email", "")

        key = "".join(random.SystemRandom().choices(KEY_ALPHABET, k=KEY_LENGTH))
        now = int(time.time())
        ttl = now + KEY_TTL_SECONDS

        item = {
            "key": key,
            "ttl": ttl,
            "generated_at": now,
            "generated_by_sub": generated_by_sub,
            "generated_by_email": generated_by_email,
        }
        registration_keys_table.put_item(Item=item)

        logger.info("Registration key generated by %s (TTL: %ds)", generated_by_email, KEY_TTL_SECONDS)
        return _response(201, {"key": key})

    except Exception:
        logger.exception("Unhandled exception")
        return _response(500, {"message": "Internal server error"})
