name: ⚠️ ⚠️ Delete All

on:
  workflow_dispatch:
    inputs:
      target_env:
        type: choice
        description: "Select environment"
        options:
          - dev
          - production

permissions:
  contents: read
  actions: write

jobs:

  delete-ui-app:
    uses: ./.github/workflows/delete-ui-app.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-cloudfront-ui:
    needs: delete-ui-app
    uses: ./.github/workflows/delete-cloudfront-ui.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-s3-ui:
    needs: delete-cloudfront-ui
    uses: ./.github/workflows/delete-s3-ui.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-dynamodb-firmware:
    uses: ./.github/workflows/delete-dynamodb-firmware.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-s3-firmware:
    uses: ./.github/workflows/delete-s3-firmware.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-func-api-health-get:
    uses: ./.github/workflows/delete-func-api-health-get.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-func-api-firmware-get:
    uses: ./.github/workflows/delete-func-api-firmware-get.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-func-api-firmware-status-patch:
    uses: ./.github/workflows/delete-func-api-firmware-status-patch.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-func-api-firmware-delete:
    uses: ./.github/workflows/delete-func-api-firmware-delete.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-func-api-ota-get:
    uses: ./.github/workflows/delete-func-api-ota-get.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-func-api-firmware-download-get:
    uses: ./.github/workflows/delete-func-api-firmware-download-get.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-func-api-users-get:
    uses: ./.github/workflows/delete-func-api-users-get.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-func-api-users-post:
    uses: ./.github/workflows/delete-func-api-users-post.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-func-api-users-delete:
    uses: ./.github/workflows/delete-func-api-users-delete.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-func-api-users-patch:
    uses: ./.github/workflows/delete-func-api-users-patch.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-api-gateway:
    needs:
      - delete-func-api-health-get
      - delete-func-api-firmware-get
      - delete-func-api-firmware-status-patch
      - delete-func-api-firmware-delete
      - delete-func-api-ota-get
      - delete-func-api-firmware-download-get
      - delete-func-api-users-get
      - delete-func-api-users-post
      - delete-func-api-users-delete
      - delete-func-api-users-patch
    uses: ./.github/workflows/delete-api-gateway.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-cloudfront:
    uses: ./.github/workflows/delete-cloudfront.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-s3-firmware-public:
    needs:
      - delete-cloudfront
    uses: ./.github/workflows/delete-s3-firmware-public.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-acm-api-gateway:
    needs:
      - delete-api-gateway
      - delete-cloudfront
      - delete-cloudfront-ui
    uses: ./.github/workflows/delete-acm-api-gateway.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-cognito:
    needs:
      - delete-api-gateway
    uses: ./.github/workflows/delete-cognito.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-func-cognito-pre-signup:
    needs:
      - delete-cognito
    uses: ./.github/workflows/delete-func-cognito-pre-signup.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-acm-cognito:
    needs:
      - delete-cognito
    uses: ./.github/workflows/delete-acm-cognito.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-dynamodb-users:
    needs:
      - delete-func-cognito-pre-signup
      - delete-func-api-users-delete
      - delete-func-api-users-post
    uses: ./.github/workflows/delete-dynamodb-users.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-func-s3-firmware-uploaded:
    needs:
      - delete-s3-firmware
    uses: ./.github/workflows/delete-func-s3-firmware-uploaded.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-func-s3-firmware-deleted:
    needs:
      - delete-s3-firmware
    uses: ./.github/workflows/delete-func-s3-firmware-deleted.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  delete-shared-layer:
    needs:
      - delete-func-s3-firmware-uploaded
      - delete-func-s3-firmware-deleted
      - delete-func-api-firmware-get
      - delete-func-api-firmware-status-patch
      - delete-func-api-firmware-delete
      - delete-func-api-ota-get
      - delete-func-api-firmware-download-get
    uses: ./.github/workflows/delete-shared-layer.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}
