name: 🚀 🚀 Deploy All

on:
  workflow_dispatch:
    inputs:
      target_env:
        type: choice
        description: "Select environment"
        options:
          - dev
          - production

permissions:
  contents: read
  actions: write

jobs:

  deploy-dynamodb-firmware:
    uses: ./.github/workflows/deploy-dynamodb-firmware.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-dynamodb-users:
    uses: ./.github/workflows/deploy-dynamodb-users.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-acm-cognito:
    uses: ./.github/workflows/deploy-acm-cognito.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-cognito-pre-signup:
    needs: deploy-dynamodb-users
    uses: ./.github/workflows/deploy-func-cognito-pre-signup.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-cognito:
    needs:
      - deploy-acm-cognito
      - deploy-func-cognito-pre-signup
    uses: ./.github/workflows/deploy-cognito.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-acm:
    uses: ./.github/workflows/deploy-acm-api-gateway.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-api-gateway:
    needs:
      - deploy-acm
      - deploy-cognito
    uses: ./.github/workflows/deploy-api-gateway.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-health-get:
    needs: deploy-api-gateway
    uses: ./.github/workflows/deploy-func-api-health-get.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-users-get:
    needs:
      - deploy-api-gateway
      - deploy-cognito
    uses: ./.github/workflows/deploy-func-api-users-get.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-users-post:
    needs:
      - deploy-api-gateway
      - deploy-dynamodb-users
    uses: ./.github/workflows/deploy-func-api-users-post.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-users-delete:
    needs:
      - deploy-api-gateway
      - deploy-cognito
      - deploy-dynamodb-users
    uses: ./.github/workflows/deploy-func-api-users-delete.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-users-patch:
    needs:
      - deploy-api-gateway
      - deploy-cognito
    uses: ./.github/workflows/deploy-func-api-users-patch.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-firmware-get:
    needs:
      - deploy-api-gateway
      - deploy-shared-layer
    uses: ./.github/workflows/deploy-func-api-firmware-get.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-firmware-status-patch:
    needs:
      - deploy-api-gateway
      - deploy-shared-layer
    uses: ./.github/workflows/deploy-func-api-firmware-status-patch.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-firmware-delete:
    needs:
      - deploy-api-gateway
      - deploy-shared-layer
    uses: ./.github/workflows/deploy-func-api-firmware-delete.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-shared-layer:
    uses: ./.github/workflows/deploy-shared-layer.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-s3-firmware-uploaded:
    needs: deploy-shared-layer
    uses: ./.github/workflows/deploy-func-s3-firmware-uploaded.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-s3-firmware-deleted:
    needs: deploy-shared-layer
    uses: ./.github/workflows/deploy-func-s3-firmware-deleted.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-s3-firmware:
    needs:
      - deploy-func-s3-firmware-uploaded
      - deploy-func-s3-firmware-deleted
    uses: ./.github/workflows/deploy-s3-firmware.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-s3-firmware-public:
    uses: ./.github/workflows/deploy-s3-firmware-public.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-cloudfront:
    needs:
      - deploy-acm
      - deploy-s3-firmware-public
    uses: ./.github/workflows/deploy-cloudfront.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-ota-get:
    needs:
      - deploy-api-gateway
      - deploy-shared-layer
      - deploy-cloudfront
    uses: ./.github/workflows/deploy-func-api-ota-get.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-firmware-download-get:
    needs:
      - deploy-api-gateway
      - deploy-shared-layer
      - deploy-s3-firmware
    uses: ./.github/workflows/deploy-func-api-firmware-download-get.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-s3-ui:
    uses: ./.github/workflows/deploy-s3-ui.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-cloudfront-ui:
    needs:
      - deploy-acm
      - deploy-s3-ui
    uses: ./.github/workflows/deploy-cloudfront-ui.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-ui-app:
    needs:
      - deploy-cloudfront-ui
      - deploy-cognito
    uses: ./.github/workflows/deploy-ui-app.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  run-integration-tests:
    needs:
      - deploy-s3-firmware
      - deploy-func-api-firmware-get
      - deploy-func-api-firmware-status-patch
      - deploy-func-api-firmware-delete
      - deploy-func-api-health-get
      - deploy-func-api-ota-get
      - deploy-func-api-firmware-download-get
      - deploy-func-api-users-get
      - deploy-func-api-users-post
      - deploy-func-api-users-delete
      - deploy-func-api-users-patch
      - deploy-ui-app
    uses: ./.github/workflows/run-integration-tests.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}