name: 🚀 Deploy dynamodb-firmware

on:
  workflow_dispatch:
    inputs:
      target_env:
        type: choice
        description: "Select environment"
        options:
          - dev
          - production
      run_tests:
        type: boolean
        description: "Run integration tests after deploy"
        default: true
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string
      run_tests:
        required: false
        type: boolean
        default: false

jobs:
  deploy-dynamodb-firmware:
    environment: ${{ inputs.target_env }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        if: ${{ !env.ACT }}
        run: pip install aws-sam-cli

      - name: Build dynamodb-firmware
        run: sam build --template-file templates/dynamodb-firmware.yaml

      - name: Deploy dynamodb-firmware
        run: |
          sam deploy \
            --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.CLOUD_FORMATION_EXECUTION_ROLE_NAME }} \
            --template-file templates/dynamodb-firmware.yaml \
            --stack-name firefly-dynamodb-firmware \
            --region ${{ secrets.AWS_REGION }} \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --s3-bucket ${{ secrets.SAM_DEPLOYMENT_BUCKET_NAME }}

  run-integration-tests:
    if: inputs.run_tests
    needs: deploy-dynamodb-firmware
    uses: ./.github/workflows/run-integration-tests.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}
