name: 🚀 Deploy dynamodb-users
on:
  workflow_dispatch:
    inputs:
      target_env:
        type: choice
        description: "Select environment"
        options:
          - dev
          - production
  workflow_call:
    inputs:
      target_env:
        required: true
        type: string

jobs:
  deploy-dynamodb-users:
    environment: ${{ inputs.target_env }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy dynamodb-users
        run: |
          aws cloudformation deploy \
            --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ vars.CLOUD_FORMATION_EXECUTION_ROLE_NAME }} \
            --template-file templates/dynamodb-users.yaml \
            --stack-name firefly-dynamodb-users \
            --no-fail-on-empty-changeset
