name: 🚀 🚀 Deploy All

on:
  workflow_dispatch:
    inputs:
      target_env:
        type: choice
        description: "Select environment"
        options:
          - dev
          - production

permissions:
  contents: read
  actions: write

jobs:

  deploy-dynamodb-firmware:
    uses: ./.github/workflows/deploy-dynamodb-firmware.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-acm:
    uses: ./.github/workflows/deploy-acm-api-gateway.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-api-gateway:
    needs: deploy-acm
    uses: ./.github/workflows/deploy-api-gateway.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-health-get:
    needs: deploy-api-gateway
    uses: ./.github/workflows/deploy-func-api-health-get.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-firmware-get:
    needs:
      - deploy-api-gateway
      - deploy-shared-layer
    uses: ./.github/workflows/deploy-func-api-firmware-get.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-firmware-status-patch:
    needs:
      - deploy-api-gateway
      - deploy-shared-layer
    uses: ./.github/workflows/deploy-func-api-firmware-status-patch.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-api-firmware-delete:
    needs:
      - deploy-api-gateway
      - deploy-shared-layer
    uses: ./.github/workflows/deploy-func-api-firmware-delete.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-shared-layer:
    uses: ./.github/workflows/deploy-shared-layer.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-s3-firmware-uploaded:
    needs: deploy-shared-layer
    uses: ./.github/workflows/deploy-func-s3-firmware-uploaded.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-func-s3-firmware-deleted:
    needs: deploy-shared-layer
    uses: ./.github/workflows/deploy-func-s3-firmware-deleted.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}

  deploy-s3-firmware:
    needs:
      - deploy-func-s3-firmware-uploaded
      - deploy-func-s3-firmware-deleted
    uses: ./.github/workflows/deploy-s3-firmware.yaml
    secrets: inherit
    with:
      target_env: ${{ inputs.target_env }}